### ISSUE TITLE
0.0.5 release?

### ISSUE THREAD

**Issue by francav** [Miragon/camunda-web-modeler#91]
@Hafflgav @dominikhorn93 
Regarding the need to incorporate the latest changes after 0.0.4 release I forked the repo, tagged 0.0.5, and published into https://www.npmjs.com/@wkspower/camunda-web-modeler. That's temporary! I will preffer to keep using miragon's repo.
Any plans on launching a 0.0.5 release? I would be happy to work on that on Miragon's repo if you want help.

**Comment by Hafflgav** [comment]
Hey @francav 
currently our time is very limited at the moment. 
I started with lifecycling of the library but did not manage to complete it yet. 

If you have already changes in place, feel free to contribute them back into this repository. 
Thanks a lot! 

Thomas

**Comment by peterhnm** [comment]
Hello @francav,
We have finished updating the libraries and released the new version `v0.1.1`.
We will now maintain this project more regularly.
So if you would like to make any changes, I would be happy to hear from you.

Regards
Peter

**Comment by francav** [comment]
Hi @peterhnm,

Thanks a lot for all that hard work! I will reach out to you if we have any sugestions.

Regards,

Victor

**Comment by francav** [comment]
New release: https://github.com/Miragon/camunda-web-modeler/releases/tag/release%2Fv0.1.0
