### ISSUE TITLE
Hidden bpmn.io icon

### ISSUE THREAD

**Issue by francav** [Miragon/camunda-web-modeler#92]
The bpmn.io icon may be hidden depending on how the canvas is displayed within embedding apps. Can we ensure that the icon is always visible, regardless of where or how the modeler is embedded in third-party apps? Should we address this within our React app, or should we escalate it to the bpmn.io team.

<img width="1511" alt="Screenshot 2024-04-25 at 10 43 11" src="https://github.com/Miragon/camunda-web-modeler/assets/85225281/f6cef7dc-2491-4de6-b4e7-597ed7b0760c">
<img width="1200" alt="Screenshot 2024-04-25 at 10 43 44" src="https://github.com/Miragon/camunda-web-modeler/assets/85225281/3e90ac4e-e4c7-4846-b9ad-060097f3b475">

**Comment by peterhnm** [comment]
Hi @francav,

There is little we can do. The icon has an absolute position, so it will always be at the bottom of the editor.
Our library will always use 100% of the container it is in.
So if you have something like below, the height of `.fill` will be `100vh` as that is the parent.
```html
<body>
  <div id="app">
    <div id="fixed"><div>
    <div id="fill"><div>
  </div>
</body>
```

```css
#app {
  height: 100vh;
}
.fixed {
  height: 100px;
}
.fill {
  height: 100%;
}
```

A fix could be to use `calc()`:
```css
.fill {
  height: calc(100% - 100px);
}
```

Or if you don't know the fixed height:
```css
#app {
  display: flex;
  flex-direction: column;
}

.fill {
  flex-grow: 1;
}
